# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Build

on:
- push

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - macos-14
        go:
        - "1.23"

      fail-fast: false
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Download font files
      run: |
        mkdir -p ~/Library/Fonts
        curl "https://p15.p3.n0.cdn.zight.com/items/eDueDDv9/a605729f-c1d2-4131-b805-e870615b43aa.ttc" -o ~/Library/Fonts/Kaiti.ttc
        #curl "https://p15.p3.n0.cdn.zight.com/items/nOuJymJQ/e6027543-de01-4698-a5f0-c600970b7ef2.ttf" -o ~/Library/Fonts/Fangsong.ttf

    - name: Setup Texlive
      uses: teatimeguest/setup-texlive-action@v3
      with:
        packages: >-
          scheme-small
          ctex
          fandol
          minted

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Setup pygmentize
      run: python3 -m pip install pygments && pygmentize -V

    - name: Check XeLaTex Version
      run: xelatex --version

    - name: Build
      run: go build -v

    - name: Test
      run: go run main.go

    - name: xelatex test
      run: xelatex -synctex 1 -interaction nonstopmode -8bit -shell-escape contract.tex
